name: CI

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  test:
    name: "Test package"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    container:
      image: ghcr.io/stertooy/gda-image:master-full

    steps:
      - uses: actions/checkout@v5
        with:
          repository: gap-packages/example
      - uses: actions/checkout@v5
        with:
          path: this-action/
      - uses: ./this-action/
