name: CI

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  test:
    name: "Test package"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          repository: gap-packages/example
      - uses: gap-actions/build-pkg@v1
      - uses: actions/checkout@v5
        with:
          path: this-action/
      - uses: ./this-action/
